(() => {
    const withAlerts = (palette) => ({
        ...palette,
        alert_success: palette.alert_success || '#22c55e',
        alert_info: palette.alert_info || '#38bdf8',
        alert_warning: palette.alert_warning || '#f59e0b',
        alert_error: palette.alert_error || '#ef4444',
    });

    const presets = {
        bootstrap: {
            label: 'Bootstrap',
            light: withAlerts({
                primary: '#0d6efd',
                secondary: '#6c757d',
                tertiary: '#0dcaf0',
                quaternary: '#6f42c1',
                background: '#ffffff',
                dark_tone_1: '#f5f5f5',
                dark_tone_2: '#11161d',
                light_tone_1: '#f8f9fa',
                light_tone_2: '#e9ecef',
                text: '#212529',
                text_background: '#ffffff',
                alert_success: '#198754',
                alert_info: '#0dcaf0',
                alert_warning: '#ffc107',
                alert_error: '#dc3545',
            }),
            dark: withAlerts({
                primary: '#0d6efd',
                secondary: '#adb5bd',
                tertiary: '#0dcaf0',
                quaternary: '#6f42c1',
                background: '#212529',
                dark_tone_1: '#1b222c',
                dark_tone_2: '#11161d',
                light_tone_1: '#495057',
                light_tone_2: '#6c757d',
                text: '#dee2e6',
                text_background: '#343a40',
                alert_success: '#198754',
                alert_info: '#0dcaf0',
                alert_warning: '#ffc107',
                alert_error: '#dc3545',
            }),
        },
        azure: {
            label: 'Azure',
            light: withAlerts({
                primary: '#0ea5e9',
                secondary: '#94a3b8',
                tertiary: '#22d3ee',
                quaternary: '#0284c7',
                background: '#f8fafc',
                dark_tone_1: '#e2e8f0',
                dark_tone_2: '#cbd5e1',
                light_tone_1: '#ffffff',
                light_tone_2: '#ffffff',
                text: '#0f172a',
                text_background: '#ffffff',
            }),
            dark: withAlerts({
                primary: '#38bdf8',
                secondary: '#334155',
                tertiary: '#22d3ee',
                quaternary: '#0ea5e9',
                background: '#020617',
                dark_tone_1: '#0b1120',
                dark_tone_2: '#070d1a',
                light_tone_1: '#1f2937',
                light_tone_2: '#334155',
                text: '#e2e8f0',
                text_background: '#0f172a',
            }),
        },
        emerald: {
            label: 'Emerald',
            light: withAlerts({
                primary: '#10b981',
                secondary: '#9ca3af',
                tertiary: '#34d399',
                quaternary: '#059669',
                background: '#f9fafb',
                dark_tone_1: '#f5fffb',
                dark_tone_2: '#78e2b4',
                light_tone_1: '#ffffff',
                light_tone_2: '#ffffff',
                text: '#111827',
                text_background: '#ffffff',
            }),
            dark: withAlerts({
                primary: '#34d399',
                secondary: '#334155',
                tertiary: '#10b981',
                quaternary: '#059669',
                background: '#071510',
                dark_tone_1: '#0b1f16',
                dark_tone_2: '#203129',
                light_tone_1: '#1f2937',
                light_tone_2: '#334155',
                text: '#e5e7eb',
                text_background: '#10251a',
            }),
        },
        moonlight: {
            label: 'Moonlight',
            light: withAlerts({
                primary: '#5b7cfa',
                secondary: '#9aa3b2',
                tertiary: '#8b9dfd',
                quaternary: '#3f57c8',
                background: '#f5f7ff',
                dark_tone_1: '#d6dcf5',
                dark_tone_2: '#b8c2e8',
                light_tone_1: '#ffffff',
                light_tone_2: '#f9fbff',
                text: '#11182e',
                text_background: '#ffffff',
            }),
            dark: withAlerts({
                primary: '#90a4ff',
                secondary: '#4a5170',
                tertiary: '#7b8bf7',
                quaternary: '#c7d2fe',
                background: '#0f1221',
                dark_tone_1: '#161a2f',
                dark_tone_2: '#0d1020',
                light_tone_1: '#2c3456',
                light_tone_2: '#3a4570',
                text: '#e6e9ff',
                text_background: '#161a2f',
            }),
        },
        rose: {
            label: 'Rose',
            light: withAlerts({
                primary: '#e11d48',
                secondary: '#9ca3af',
                tertiary: '#fb7185',
                quaternary: '#be123c',
                background: '#fff1f2',
                dark_tone_1: '#fecdd3',
                dark_tone_2: '#fda4af',
                light_tone_1: '#ffffff',
                light_tone_2: '#ffffff',
                text: '#4c0519',
                text_background: '#ffffff',
            }),
            dark: withAlerts({
                primary: '#fb7185',
                secondary: '#374151',
                tertiary: '#f43f5e',
                quaternary: '#e11d48',
                background: '#1b0a11',
                dark_tone_1: '#2e1220',
                dark_tone_2: '#1e0b14',
                light_tone_1: '#3b1f2a',
                light_tone_2: '#5b2137',
                text: '#ffe4e6',
                text_background: '#2e1220',
            }),
        },
        amber: {
            label: 'Amber',
            light: withAlerts({
                primary: '#d97706',
                secondary: '#a3a3a3',
                tertiary: '#fbbf24',
                quaternary: '#b45309',
                background: '#fffbeb',
                dark_tone_1: '#fde68a',
                dark_tone_2: '#fcd34d',
                light_tone_1: '#ffffff',
                light_tone_2: '#ffffff',
                text: '#451a03',
                text_background: '#ffffff',
            }),
            dark: withAlerts({
                primary: '#f59e0b',
                secondary: '#3f3f46',
                tertiary: '#fbbf24',
                quaternary: '#d97706',
                background: '#1c1405',
                dark_tone_1: '#2f2108',
                dark_tone_2: '#1d1405',
                light_tone_1: '#3f2d0d',
                light_tone_2: '#713f12',
                text: '#fef3c7',
                text_background: '#2f2108',
            }),
        },
        slate: {
            label: 'Slate',
            light: withAlerts({
                primary: '#475569',
                secondary: '#94a3b8',
                tertiary: '#64748b',
                quaternary: '#334155',
                background: '#f8fafc',
                dark_tone_1: '#e2e8f0',
                dark_tone_2: '#cbd5e1',
                light_tone_1: '#ffffff',
                light_tone_2: '#ffffff',
                text: '#0f172a',
                text_background: '#ffffff',
            }),
            dark: withAlerts({
                primary: '#94a3b8',
                secondary: '#475569',
                tertiary: '#64748b',
                quaternary: '#cbd5e1',
                background: '#0f172a',
                dark_tone_1: '#020617',
                dark_tone_2: '#01030c',
                light_tone_1: '#334155',
                light_tone_2: '#475569',
                text: '#e2e8f0',
                text_background: '#1e293b',
            }),
        },
        purple: {
            label: 'Purple',
            light: withAlerts({
                primary: '#7c3aed',
                secondary: '#9ca3af',
                tertiary: '#a855f7',
                quaternary: '#6d28d9',
                background: '#f7f2ff',
                dark_tone_1: '#ddd6fe',
                dark_tone_2: '#c4b5fd',
                light_tone_1: '#ffffff',
                light_tone_2: '#fdfaff',
                text: '#2e1065',
                text_background: '#ffffff',
            }),
            dark: withAlerts({
                primary: '#a855f7',
                secondary: '#4c1d95',
                tertiary: '#c084fc',
                quaternary: '#d8b4fe',
                background: '#140828',
                dark_tone_1: '#1f0d3c',
                dark_tone_2: '#16082c',
                light_tone_1: '#3b1a74',
                light_tone_2: '#4c1d95',
                text: '#f3e8ff',
                text_background: '#1f0d3c',
            }),
        },
    };

    class ThemeEditorPresets {
        static all() {
            return presets;
        }
    }

    window.ThemeEditorPresets = ThemeEditorPresets;
})();
