<?php

return [
    'type' => 'custom-feature-cards',
    'label' => 'Feature cards',
    'description' => '4 cartes features customisables.',
    'view' => 'components.render.custom.feature-cards',
    'placements' => ['body'],
    'scopes' => ['global', 'page'],
    'defaults' => [
        'title' => 'Pourquoi nous rejoindre ?',
        'subtitle' => 'Une expérience pensée pour la progression.',
        'feature_1_icon' => 'bi bi-lightning-charge-fill',
        'feature_1_title' => 'Gameplay',
        'feature_1_text' => 'Système de progression unique.',
        'feature_2_icon' => 'bi bi-people-fill',
        'feature_2_title' => 'Communauté',
        'feature_2_text' => 'Une base de joueurs active.',
        'feature_3_icon' => 'bi bi-trophy-fill',
        'feature_3_title' => 'Compétition',
        'feature_3_text' => 'Saisons et classements.',
        'feature_4_icon' => 'bi bi-gem',
        'feature_4_title' => 'Récompenses',
        'feature_4_text' => 'Skins, titres et bonus.',
    ],
    'fields' => [
        ['key' => 'title', 'type' => 'text', 'label' => 'Titre'],
        ['key' => 'subtitle', 'type' => 'text', 'label' => 'Sous-titre'],
        ['key' => 'feature_1_icon', 'type' => 'text', 'label' => 'Feature 1 icône'],
        ['key' => 'feature_1_title', 'type' => 'text', 'label' => 'Feature 1 titre'],
        ['key' => 'feature_1_text', 'type' => 'textarea', 'label' => 'Feature 1 texte'],
        ['key' => 'feature_2_icon', 'type' => 'text', 'label' => 'Feature 2 icône'],
        ['key' => 'feature_2_title', 'type' => 'text', 'label' => 'Feature 2 titre'],
        ['key' => 'feature_2_text', 'type' => 'textarea', 'label' => 'Feature 2 texte'],
        ['key' => 'feature_3_icon', 'type' => 'text', 'label' => 'Feature 3 icône'],
        ['key' => 'feature_3_title', 'type' => 'text', 'label' => 'Feature 3 titre'],
        ['key' => 'feature_3_text', 'type' => 'textarea', 'label' => 'Feature 3 texte'],
        ['key' => 'feature_4_icon', 'type' => 'text', 'label' => 'Feature 4 icône'],
        ['key' => 'feature_4_title', 'type' => 'text', 'label' => 'Feature 4 titre'],
        ['key' => 'feature_4_text', 'type' => 'textarea', 'label' => 'Feature 4 texte'],
    ],
];
